### PR TITLE
Automatically cut protocol and path at the search

### PR DESCRIPTION
**Pull request by Maaaathis**
It will automatically remove all HTTP & HTTPS protocols that are at the beginning of a target search URL.

So URL's can be copied and entered directly from the browser without annoying reformatting and removing of the protocol.

### CODE REVIEW

**Comment by feliskio** [comment]
Hi @Maaaathis, thanks for the suggestion!

I think the utility of this could be even greater when using `new URL('...').hostname` as this would also allow for non-http protocols as well as full addresses including a path to be pasted.

**Comment by feliskio** [comment]
I believe `new URL('...')` throws an error if the input string is malformatted. Should probably catch that error.

**Comment by Maaaathis** [comment]
Heyy @feliskio, of course that makes even more sense directly. I have implemented this once. 
If it is not a correct URL, the part is simply skipped and validated normally.

**Comment by feliskio** [comment]
Thanks again @Maaaathis! I appreciate the attention to detail with label.

**Pull request merged**
